### ISSUE TITLE
document query string parameters in -h usage docs

### ISSUE THREAD

**Issue by wolfgangmeyers** [danielgtaylor/restish#51]
I've specified query string parameters in my openapi document:

```yaml
 /jobs/{id}/results:
    get:
      description: Get a list of results for a job
      operationId: listJobResults
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          required: false
          schema:
            type: integer
        - name: direction
          in: query
          required: false
          schema:
            type: string
            enum: [forward, reverse]
```

It would be nice if in this case, "cursor" and "direction" were available as flags to be passed to the api. I know I can pass them with the -q flag, but there isn't any documentation about the query string params when printing usage docs with -h.
