### ISSUE TITLE
Profiles break when `openapi.servers` is defined

### ISSUE THREAD

**Issue by kyranjamie** [danielgtaylor/restish#60]
Spent some time trying to figure out why API generated from a flattened openapi spec wouldn't work.

Cmd such as `restish hiro get-status` returns `ERROR: Caught error: Get "https://extended/v1/status": dial tcp: lookup extended on 8.8.8.8:53: no such host`

On deletion of 

```yaml
servers:
  - url: https://stacks-node-api.mainnet.stacks.co/
    description: Mainnet
  - url: https://stacks-node-api.testnet.stacks.co/
    description: Testnet
  - url: http://localhost:3999/
    description: Local
```

The command works

<details>
<summary>Restish spec</summary>

```
{
  "hiro": {
    "base": "https://stacks-node-api.mainnet.stacks.co/",
    "spec_files": ["openapi.yaml"]
  }
}
```

</details>
